use axum::response::Html;

pub async fn admin_page() -> Html<&'static str> {
    Html(ADMIN_HTML)
}

const ADMIN_HTML: &str = r##"<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>阴阳师寄养 · 控制台</title>
<style>
:root{color-scheme:dark;--bg:#151719;--panel:#1d2023;--line:#34393e;--text:#e7e9ea;--muted:#92989e;--green:#8fae9c;--red:#df8d84}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC",sans-serif}main{max-width:960px;margin:auto;padding:28px 18px 60px}header{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}h1{font-size:22px;margin:0}h2{font-size:16px;margin:0 0 12px}.muted{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.card{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:18px}.wide{grid-column:1/-1}.state{display:flex;gap:10px;align-items:center}.dot{width:9px;height:9px;border-radius:50%;background:#777}.online{background:#7fc29a}.offline{background:var(--red)}button{background:#303a34;border:1px solid #506158;color:var(--text);padding:9px 13px;border-radius:7px;cursor:pointer}button:disabled{opacity:.5}label{display:block;margin:12px 0 4px;color:var(--muted)}input{width:100%;padding:9px 10px;background:#151719;color:var(--text);border:1px solid var(--line);border-radius:6px;font:inherit}.formgrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 12px}#message{min-height:22px;margin-top:10px;color:var(--muted)}#result a{color:var(--green);word-break:break-all}.small{font-size:12px;color:var(--muted)}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:9px;border-bottom:1px solid var(--line)}th{color:var(--muted);font-weight:500}@media(max-width:640px){.grid,.formgrid{grid-template-columns:1fr}.wide{grid-column:auto}header{align-items:flex-start;gap:12px;flex-direction:column}}
</style></head><body><main>
<header><div><h1>阴阳师寄养控制台</h1><div class="muted">本机管理页面 · 状态每 5 秒自动刷新</div></div><button id="refresh">立即刷新</button></header>
<div class="grid">
<section class="card"><h2>服务状态</h2><div class="state"><i id="serverDot" class="dot"></i><span>后端</span><strong id="serverState">检查中…</strong></div><div class="state" style="margin-top:10px"><i id="agentDot" class="dot"></i><span>Agent</span><strong id="agentState">检查中…</strong></div><div id="hostMeta" class="small" style="margin-top:12px"></div></section>
<section class="card"><h2>扫码登录</h2><div class="formgrid"><div><label for="customerId">客户编号</label><input id="customerId" type="number" min="1" value="10005"></div><div><label for="days">服务天数</label><input id="days" type="number" min="1" value="30"></div><div><label for="ttl">扫码链接有效分钟</label><input id="ttl" type="number" min="1" max="1440" value="30"></div><div><label for="plan">套餐代码</label><input id="plan" value="BASIC_AUTO_FOSTER"></div></div><div style="margin-top:14px"><button id="create">分配模拟器并创建扫码登录</button></div><div id="message"></div><div id="result"></div><div class="small">Agent 和空闲模拟器在线后才能创建登录会话。</div></section>
<section class="card wide"><h2>模拟器</h2><div id="emulators" class="muted">正在获取设备…</div></section>
<section class="card wide"><h2>使用说明</h2><div class="muted">确认后端、Agent 和模拟器都在线，再创建扫码登录。二维码页面可复制链接发给客户。Agent 的运行日志在另一个控制台窗口。</div></section>
</div></main><script>
const token=new URLSearchParams(location.hash.slice(1)).get('token');const $=id=>document.getElementById(id);
async function api(path,options={}){const response=await fetch(path,{...options,headers:{...(options.headers||{}),Authorization:'Bearer '+(token||''),'Content-Type':'application/json'}});if(!response.ok){let detail='HTTP '+response.status;try{const body=await response.json();detail=body.message||body.error||detail}catch{}throw new Error(detail)}return response.json()}
function setState(id,ok,label){$(id+'Dot').className='dot '+(ok?'online':'offline');$(id+'State').textContent=label}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function refresh(){try{const r=await fetch('/readyz',{cache:'no-store'});setState('server',r.ok,r.ok?'在线':'离线')}catch{setState('server',false,'无法连接')}if(!token){setState('agent',false,'管理凭据缺失');$('hostMeta').textContent='请从本机一键启动器打开此页面';$('emulators').textContent='没有管理凭据';return}try{const hosts=await api('/admin/hosts');const host=hosts[0];if(!host){setState('agent',false,'未登记主机');$('hostMeta').textContent='';$('emulators').textContent='没有登记的模拟器主机';return}const online=host.status==='ONLINE';setState('agent',online,online?'在线':'离线');$('hostMeta').textContent=host.hostname+' · '+host.onlineEmulators+'/'+host.totalEmulators+' 台在线 · 可用容量 '+host.configuredCapacity;const devices=await api('/admin/hosts/'+host.id+'/emulators');$('emulators').innerHTML=devices.length?'<table><thead><tr><th>设备</th><th>ADB 地址</th><th>状态</th><th>账号容量</th><th>已绑定</th></tr></thead><tbody>'+devices.map(d=>'<tr><td>'+escapeHtml(d.emulatorCode)+'</td><td>'+escapeHtml(d.adbSerial||'—')+'</td><td>'+escapeHtml(d.status)+'</td><td>'+escapeHtml(d.maxAccountCount)+'</td><td>'+escapeHtml(d.boundAccounts)+'</td></tr>').join('')+'</tbody></table>':'暂未发现设备'}catch(error){setState('agent',false,'状态读取失败');$('hostMeta').textContent=error.message;$('emulators').textContent='读取失败：'+error.message}}
async function create(){const button=$('create');button.disabled=true;$('message').textContent='正在分配空闲模拟器并创建登录会话…';$('result').textContent='';try{const data=await api('/admin/onboard',{method:'POST',body:JSON.stringify({customerId:Number($('customerId').value),planCode:$('plan').value.trim(),serviceDays:Number($('days').value),loginTtlMinutes:Number($('ttl').value)})});const customerOrigin='http://j55d6643.natappfree.cc';const login=new URL(data.loginUrl,customerOrigin).href;const service=new URL(data.serviceUrl,customerOrigin).href;$('message').textContent='登录会话已创建（'+data.loginDispatchStatus+'）';$('result').innerHTML='<p><a href="'+escapeHtml(login)+'" target="_blank" rel="noopener">打开客户扫码页面（外网）</a></p><p class="small">'+escapeHtml(login)+'</p><p><a href="'+escapeHtml(service)+'" target="_blank" rel="noopener">打开服务控制页面（外网）</a></p><button id="copy">复制客户扫码链接</button>';$('copy').onclick=async()=>{await navigator.clipboard.writeText(login);$('message').textContent='客户扫码链接已复制'};await refresh()}catch(error){$('message').textContent='创建失败：'+error.message}finally{button.disabled=false}}
if(!token){$('message').textContent='管理凭据缺失，请从本机一键启动器打开控制台'}$('refresh').onclick=refresh;$('create').onclick=create;refresh();setInterval(refresh,5000);
</script></body></html>"##;
